### PR TITLE
Brandon deploy

### PR DESCRIPTION
**Pull request by branflake2267**
Goal of this branch is to use of 'mvn clean integration-test deploy' to deploy snapsnot and showcase to gae. 

gwt-dev is needed for testing 'mvn clean integration-test'

refractor of tests to match maven naming for tests.

### CODE REVIEW

**Comment by branflake2267** [comment]
https://github.com/branflake2267/GWT-Maps-V3-Api/issues/12

**Comment by branflake2267** [comment]
Still tuning this, not ready yet. hmn

**Comment by branflake2267** [comment]
mvn gwt:run works

**Comment by branflake2267** [comment]
I broke version 50, reverted gae back to 49. Looks like I got it back on the right track for auto deploying... testing and retesting. :)

**Comment by branflake2267** [comment]
mvn clean gwt:compile deploy -DskipTests - works for deploying to gae

**Comment by branflake2267** [comment]
Just a note, I changed index.html to showcase.html b/c it seems to match the css naming and module naming and then shows up with the showcase.html in the gwt plugin in eclipse. 

I'm closing in on having everything work smoothly in the poms :)

**Comment by branflake2267** [comment]
Looks like I have all the steps working finally and now testing them together. The tests were running slow, so I got it to  ignore and run only the suite. 

'mvn clean integration-test gwt:compile deploy' will test the gwt tests then compile and deploy snapshot and upload to gae

**Comment by branflake2267** [comment]
One more note, I moved a few things from the parent pom into both the children, so they seem duplicated, but I think it should help with copying the project type settings into single project setups. I also think it should help the GWT eclipse plugin get setup when importing. It feels a bit redundant, but I think it will help copy pasting. :)

**Comment by branflake2267** [comment]
Wahoo, all worked with 'mvn clean integration-test gwt:compile deploy'. I'm going to push to master and test this with the build server.

**Comment by twistedpair** [comment]
Nice! Can you update the wiki we have on how to build the app for contributors? This should make it much easier for folks.

**Comment by branflake2267** [comment]
Great point. Thats my goal. I want to make it super transparent for anybody. I've been doing the same with GWTP build to sonatype too. I can trade notes back in forth until I can get it honed to super easy. I've been messing with the build tuning on the server a little so I know it works on reboot.

**Comment by branflake2267** [comment]
My aim is to come back in the after work.

**Pull request merged**
