### PR TITLE
Added new implementer project: Open City Agora

### PR DESCRIPTION
**Pull request by jorgelamb**
Hi,

As explained in an issue #98 I've added our project using this library in the implementer list.

If you think something from our project would be interesting in the showcase page just let us know and we'll try to add it, but it's basically adding multiple things already in the showcase over the same map.

We submitted our project to Google Places API Developer Challenge. You can check all the projects there and vote for the ones you like in the gallery page: https://developers.google.com/places/challenge/gallery

Thanks,
Jorge

### CODE REVIEW

**Comment by branflake2267** [comment]
LGTM :)

**Comment by branflake2267** [comment]
Can you catch your branch up with the master by merge with master? Then I can auto merge here.

**Comment by jorgelamb** [comment]
OK, I will have a look when I can.

J

**Comment by jorgelamb** [comment]
Merged with master. I thought I had already done it but because the operation had failed at first because of some uncommitted change.

**Pull request merged**
