### PR TITLE
Improved overlayview sample

### PR DESCRIPTION
**Pull request by sonytricoire**
added custom overlay
show problem with methods argument which is null in onRemove handler

### CODE REVIEW

**Comment by branflake2267** [comment]
It's hard to tell what has changed. I reformatted the entire project hoping to avoid this, but seems it didn't work on this. 

Good job. I'll have to take a look once I can compare the difference locally. :)

**Comment by branflake2267** [comment]
O wait, thats the samples. I don't think I reformatted that part. oops. My bad.

**Comment by branflake2267** [comment]
Awesome, its a sample! Its sinking in now. Nice job!

**Comment by twistedpair** [comment]
@branflake2267 FWIW, adding **?w=1** to the Github URL [will not show whitespace differences](https://github.com/blog/967-github-secrets). That being said, I don't see why they don't add a button for that, given we now have _zen mode_ buttons.

**Comment by branflake2267** [comment]
Cool, thanks for the secret :)

**Comment by wikiro** [comment]
where can i see the showcase?

**Comment by twistedpair** [comment]
We could place a showcase on the [`gh-pages branch`](https://github.com/branflake2267/GWT-Maps-V3-Api/tree/gh-pages)  and use the site plugin to auto deploy the showcase there on each build. This way we could have each build deployed, not just the current head on gae.

**Comment by branflake2267** [comment]
Its deployed automatically if the tests pass to app engine on each master commit update. :)

**Comment by branflake2267** [comment]
http://teamcity.gonevertical.org/viewLog.html?buildId=211&tab=buildResultsDiv&buildTypeId=bt5 couple tests are failing.

**Comment by branflake2267** [comment]
@evmx here is the showcase: http://gonevertical-apis.appspot.com/

**Comment by twistedpair** [comment]
Cool, nice work. Not sure about those tests. Didn't change anything but the header for the docs. I think they'll pass on the next run.

**Comment by branflake2267** [comment]
yeah, something strange just popup up I think. I had them all running on my last commit. Although I've had a hard time with the double precision, so I've generified a couple of them, thinking that the source library is taking care of the precision tests. Anyway, its probably something simple. I haven't had time yet to help, aiming to do some on this weekend. oh, one more thing, some of the tests behave differently when ran as a group than when ran individually, so they trick me into thinking there running until I run the suite.

**Comment by twistedpair** [comment]
@branflake2267 yes, unfortunately I've had to reorder some of them in the past to get them to run correctly. I believe it is an issue with HtmlUnit and JS/lib's.

**Comment by branflake2267** [comment]
no problem I thought you added a nice method related to that. It seems on the version upgrade to 3.10 seems shift a little too.

**Comment by branflake2267** [comment]
Looks good to me, I'll merge and push to master.

**Pull request merged**
