### PR TITLE
Added basic implementation of AutocompleteService

### PR DESCRIPTION
**Pull request by meriouma**

### CODE REVIEW

**Comment by meriouma** [comment]
Not sure why it's all failing like that.. I haven't changed much stuff. Do you know what might be going on @branflake2267 ?

**Comment by branflake2267** [comment]
I did just reboot the server, so maybe it caught up.

**Comment by branflake2267** [comment]
Rerunning it, I changed the update github configuration, so the details should like to the build.

**Comment by meriouma** [comment]
Seems to be related with htmlunit. I can't run the tests on local either

**Comment by branflake2267** [comment]
Looks good, would you have time to add a simple test?

**Comment by meriouma** [comment]
Yeah, I'll try

**Comment by branflake2267** [comment]
looks like unpack is having an issue > net.kindleit:maven-gae-plugin:0.9.5:unpack

**Comment by meriouma** [comment]
I added 2 basic tests

**Comment by branflake2267** [comment]
Nice Job. I'm working on updating GAE so it will build.

**Comment by meriouma** [comment]
Thank you Brandon!

**Comment by branflake2267** [comment]
Welcome, thanks for contributing. Let me know when you need a release so I can plan that. :)

**Comment by meriouma** [comment]
No problem! Ok, well for now we're good with the snapshot!

**Pull request merged**
