### PR TITLE
Brandon gwt upgrade

### PR DESCRIPTION
**Pull request by branflake2267**
This removes all unnecessary files produced by eclipse on setup. I modified the directions to show how to setup eclipse test project in the wiki. Instead I can use mvn eclipse:eclipse... Anyway, this gets rid of what we don't need.

### CODE REVIEW

**Comment by branflake2267** [comment]
Are you using IDEA?

**Comment by twistedpair** [comment]
Good work. Those did need to be cleaned out. I'm not using IDEA, are you?

**Comment by branflake2267** [comment]
I'm using eclipse. But I do use IDEA for some things at work since they prefer it. I thought I'd ask b/c there is a couple ways to go with eclipse setup, which I prefer a more manual setup so I can override the maven dependencies, but I like maven taken care of the setup.

**Comment by branflake2267** [comment]
Thanks. :)

**Comment by twistedpair** [comment]
Since you made this issue and the pull, can it be closed, or is there more work to be done?

**Comment by branflake2267** [comment]
Yeah, I thought you might want to have a looksee. I'll merge it then.

**Pull request merged**
