### PR TITLE
Added cities and regions to AutocompleteType

### PR DESCRIPTION
**Pull request by meriouma**

### CODE REVIEW

**Comment by branflake2267** [comment]
Right on. Good job!

**Comment by branflake2267** [comment]
Do you think you could add a test for that?

**Comment by meriouma** [comment]
I added a few tests

**Comment by branflake2267** [comment]
Wow, good job. LGTM :)

**Comment by meriouma** [comment]
I'm just wondering, at which frequency do you release snapshots?

**Comment by branflake2267** [comment]
They should build on each master update.

**Comment by branflake2267** [comment]
http://teamcity.gonevertical.org/viewType.html?buildTypeId=bt5

**Pull request merged**
