### PR TITLE
Javadoc pages added

### PR DESCRIPTION
**Pull request by twistedpair**
All releases > 3.8.0 were not online in javadoc form. Add them. Built with JDK 1.7 (IcedTea) so that we get the _nicer_ format and styles. Added logic to show the Follow us link only on the core page and placed back on GA tracking so we can see who is using the docs and which methods are the most popular/confusing.

### CODE REVIEW

**Comment by branflake2267** [comment]
Good job. Sorry but I think I removed some stuff from pom related to that to launch. I'm wondering if it is possible to auto deploy this using the github maven plugin for ghsites. I'm curious how you do that and if its possible to write up some steps to how you do that? Nice work!

**Comment by twistedpair** [comment]
@branflake2267  Good point. Obviously the autodeploy bit using the plugin would be optimal. Since I had to do some tweaks to the old tags to get things looking right, that cannot be automated. Going forward I'll need to figure out how to do it that way.

**Comment by twistedpair** [comment]
Added a [tutorial](https://github.com/branflake2267/GWT-Maps-V3-Api/wiki/Javadoc-Tutorial) on how this was done.

**Comment by branflake2267** [comment]
nice job! thank you :)

**Pull request merged**
