### PR TITLE
Show case updates

### PR DESCRIPTION
**Pull request by cyclingthealps**
My first contribution to the Maps API.
I added a Map Widget where you can load and unload multiple kml to a map.
A preview of this map can be found [here](http://1.maps-api-additional.appspot.com/)

Dennis

### CODE REVIEW

**Comment by branflake2267** [comment]
LGTM :+1:

**Comment by branflake2267** [comment]
Good job and thanks for adding to the showcase!

**Comment by twistedpair** [comment]
Nice work @cyclingthealps ! Keep up the great work with your site. :+1:

**Comment by cyclingthealps** [comment]
Cool you guys like it!!
Time to deploy the new showcases @branflake2267 :-)

**Pull request merged**
