### PR TITLE
Added conditional logic and GH links to header of docs plugin

### PR DESCRIPTION
**Pull request by twistedpair**
Simple update to get modern looking javadocs with a GH link and the GA tracking to see what people are looking at and what the methods of interest/confusion are.

### CODE REVIEW

**Comment by branflake2267** [comment]
Good job. sorry about removing some of that. :) I think I filed an issue for it. At the time I was having issues deploying to sonatype.

**Comment by branflake2267** [comment]
Do any links in home readme need to be updated to javadocs?

**Comment by twistedpair** [comment]
Already did it. And in wiki. ;)
Sick day from work, so knocking off some low hanging fruit.

**Comment by branflake2267** [comment]
Nice :)

**Pull request merged**
