### PR TITLE
Brandon showcase

### PR DESCRIPTION
**Pull request by branflake2267**
This refactors the directories to match the pom. And feel free to critque the naming, I'm not particulary tied to these, but I've been wanting to get something a little more consistent. The goal of this is to allow maven import from eclipse or idea to do the setup automatcially, no more messing with the build path. 

**TODO**
I need to refractor the main core into maven directory, but haven't go there yet. Maybe better to wait till towards end of 3.9.0. 

**What I did:**
1. tuned the pom.xml parent and children
2. named the modules 
- gwt-maps
- gwt-maps-api
- gwt-maps-showcase
- renamed the two showcase and api directories to that of the pom.xml module
- I changed out the showcase pom.xml matching one of our other app engine projects, which allows us to use jenkins to deploy, but any ci server could now deploy the isntance with mvn gae:deploy. 

The coolest part is we can right click on egit working directory and import maven projects and all 3 projects get setup and it configures the GWT eclipse plugin with GWT and app engine. The other maven import method is using maven to import the project, but I like using the egit shortcut. 

**To test it out.**
1. mvn eclipse:clean
2. remove .settings directories in the paths
3. load up eclipse and goto egit and right click on working directory and import as maven projects, if you don't have this, you'll need m2e for egit. 

I had one minor issue with my setup but I think its osx related and will get at it later.

### CODE REVIEW

**Comment by branflake2267** [comment]
I fixed the pom.xml java version, which now everything setups correctly for me. Wahoo. :)

**Comment by branflake2267** [comment]
One more note, to update maven its right click, maven update project.

**Comment by branflake2267** [comment]
Shoot I forgot to run the tests.

**Comment by twistedpair** [comment]
From your last comment, it is unclear if this is ready to be merged. Otherwise, LGTM :+1:

**Comment by branflake2267** [comment]
I'll test tonight

**Pull request merged**
